# Generated by Django 5.2.3 on 2025-06-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Shoes'), ('Clothing', 'Clothing'), ('Electronics', 'Electronics'), ('Others', 'Others')], max_length=25),
        ),
    ]
